version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: switch
          command: cd src
      - run:
          name: Dependencies
          command: dotnet restore
      - run:
          name: Tests
          command: |
                   dotnet test AssertNet.Core.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=bin
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -f "AssertNet.Core.Tests/bin/coverage.xml" -t $CODECOV_KEY
