version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
                   cd src
                   dotnet restore
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test
      - run:
          name: Codecov
          command: |
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Core.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Tests.Xunit/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Tests.Nunit/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Tests.MsTest/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Moq.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
