version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
                   cd src
                   dotnet restore
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./bin/ /p:Exclude="[xunit*]*"
      - run:
          name: Codecov
          command: |
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Core.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Xunit.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.NUnit.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.MSTest.Tests/bin/coverage.opencover.xml" -t $CODECOV_KEY
